### ISSUE TITLE
fragment parameter is optional, yet it type isn't

### ISSUE THREAD

**Issue by pjljvandelaar** [BurritoZz/Haystack#13]
When looking at

https://github.com/BurritoZz/Haystack/blob/4d35fd50ef8f6b15c5490e4ab6dd523a3c21dca3/searchresult.py#L73

I see that fragment is a parameter of type boolean with default value False: so it will always be present (also when not specified).
However the documentation specifies something else...

What does mypy tell you?

**Comment by BurritoZz** [comment]
I agree that this doesn't make sense. That was a function which did two separate things depending on whether the flag was true or false, so it should really have been two separate functions.
In the parse confirm branch this function has been split in two, I'm awaiting approval to merge this into main.
