### ISSUE TITLE
Consider hiding iteration

### ISSUE THREAD

**Issue by pjljvandelaar** [BurritoZz/Haystack#14]
On line
https://github.com/BurritoZz/Haystack/blob/4d35fd50ef8f6b15c5490e4ab6dd523a3c21dca3/searchresult.py#L47

I see an explicit iteration over two list of equal length.
You arbitrary chose one list to determine the range.

Have you considered using [zip](https://www.w3schools.com/python/ref_func_zip.asp) and [all](https://www.w3schools.com/python/ref_func_all.asp) and a simple ([lambda](https://www.w3schools.com/python/python_lambda.asp)) function to check for equality
to hide the iteration?

**Comment by pjljvandelaar** [comment]
For inspiration look at: https://stackoverflow.com/questions/9766608/zipwith-analogue-in-python

**Comment by BurritoZz** [comment]
Solved by: https://github.com/BurritoZz/Haystack/pull/33/commits/269f1923ef2ea7fec63009193dd38eacac013036
